export default {
    id: 1,
    type: 'carousel',
    name: '01 Theken Screen',
    theme: 'dark',
    horizontal_resolution: 1080,
    vertical_resolution: 1920,
    view_order: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],
    views: [
        {
            id: 1,
            name: 'TraBS Poster 1',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'TraBS Poster 1',
                    description: null,
                    background: '/images/poster/trabs_1.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 2,
            name: 'TraBS Poster 2',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'TraBS Poster 2',
                    description: null,
                    background: '/images/poster/trabs_2.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 3,
            name: 'TraBS Poster 3',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'TraBS Poster 3',
                    description: null,
                    background: '/images/poster/trabs_3.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 4,
            name: 'Kids Play Date',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'Kids Play Date',
                    description: null,
                    background: '/images/poster/kids_play_date.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 5,
            name: 'Neues Dach',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'Neues Dach',
                    description: null,
                    background: '/images/poster/neues_dach.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 6,
            name: 'wlan',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'wlan',
                    description: null,
                    background: '/images/poster/wlan.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 7,
            name: 'Aufruf Kneipenabend',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'Aufruf Kneipenabend',
                    description: null,
                    background: '/images/poster/aufruf_kneipenabend.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 8,
            name: 'Aufruf Plakate',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'Aufruf Plakate',
                    description: null,
                    background: '/images/poster/aufruf_plakate.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 9,
            name: 'echt 1',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'echt 1',
                    description: null,
                    background: '/images/poster/echt_1.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 10,
            name: 'echt 2',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'echt 2',
                    description: null,
                    background: '/images/poster/echt_2.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 11,
            name: 'echt 3',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'echt 3',
                    description: null,
                    background: '/images/poster/echt_3.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 12,
            name: 'echt 4',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'echt 4',
                    description: null,
                    background: '/images/poster/echt_4.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 13,
            name: 'echt 5',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'echt 5',
                    description: null,
                    background: '/images/poster/echt_5.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 14,
            name: 'echt 1',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 1, 2, 3, 4, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'echt 1',
                    description: null,
                    background: '/images/poster/hateshield.png',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 15,
            name: 'Fetisch Friends 1',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'Fetisch Friends 1',
                    description: null,
                    background: '/images/poster/fetisch_1.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
        {
            id: 16,
            name: 'Fetisch Friends 2',
            duration: 30000,
            stagger: 100,
            from_date: null,
            from_time: null,
            to_date: null,
            to_time: null,
            on_days: [0, 5, 6],
            components: [
                {
                    type: 'fullscreen_image',
                    title: 'Fetisch Friends 2',
                    description: null,
                    background: '/images/poster/fetisch_2.jpg',
                    foreground: null,
                    items: [],
                },
            ],
        },
    ],
}